// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetVersion():Promise<string>;

export function LoadCollections():Promise<Array<main.Collection>>;

export function SaveCollections(arg1:Array<main.Collection>):Promise<void>;

export function SendRequest(arg1:main.APIRequest):Promise<main.APIResponse>;
